"""Stable learner artifact filenames; importing names never loads builders."""

STUDY_ORCHESTRATION_CONTEXT = '26_r17_study_orchestration_context.json'
DAILY_STUDY_CARD = '27_r17_daily_study_card.json'
REVIEW_FOLLOWUPS = '28_r17_review_followups.json'
WEEKLY_ORCHESTRATION = '29_r17_weekly_orchestration.json'
R17_TEACHER_LOOP_ARTIFACT = '30_r17_teacher_loop_acceptance_artifact.json'
ADAPTIVE_COACHING_CONTEXT = '31_r18_adaptive_coaching_context.json'
ADAPTIVE_COACHING_PACKET = '32_r18_adaptive_coaching_packet.json'
COACHING_FEEDBACK_LOOP = '33_r18_coaching_feedback_loop.json'
CLOSED_LOOP_OPERATIONS = '34_r18_closed_loop_operations.json'
R18_ADAPTIVE_COACHING_ARTIFACT = '35_r18_adaptive_coaching_acceptance_artifact.json'
LONGITUDINAL_TUTORING_CONTEXT = '36_r19_longitudinal_tutoring_context.json'
TUTORING_STRATEGY_PACKET = '37_r19_tutoring_strategy_packet.json'
TUTORING_FEEDBACK_LOOP = '38_r19_tutoring_feedback_loop.json'
LONG_HORIZON_OPERATIONS = '39_r19_long_horizon_operations.json'
R19_LONGITUDINAL_TUTORING_ARTIFACT = '40_r19_longitudinal_tutoring_acceptance_artifact.json'
AUTONOMOUS_TRIGGER_CONTRACT = '41_r20_autonomous_trigger_contract.json'
AUTONOMOUS_ACTION_PLAN = '42_r20_autonomous_action_plan.json'
AUTONOMOUS_GOVERNANCE_LEDGER = '43_r20_autonomous_governance_ledger.json'
R20_AUTONOMOUS_TUTORING_ARTIFACT = '44_r20_autonomous_tutoring_acceptance_artifact.json'
